# test:
#   image: julia:1.12
#   script:
#     - chmod +x engines/MzingaEngine engines/nokamute
#     - julia --project=. -e "using Pkg; Pkg.instantiate()"
#     - julia --project=. -e "using Pkg; Pkg.add([\"Test\", \"TestItems\", \"TestItemRunner\"])"
#     - julia --project=. -e "using Pkg; Pkg.test()"

build_linux:
  image: julia:1.12
  script: 
    - apt-get update && apt-get install -y clang make
    - julia --project=. -e "using Pkg; Pkg.instantiate(); Pkg.add(\"JuliaC\")"
    - >
      julia --project=. --startup-file=no -e "using JuliaC; JuliaC.main(ARGS)" --
      --output-exe intsect
      --bundle engines/intsect-linux-build
      --trim=safe
      --experimental
      .
  artifacts:
    paths:
      - engines/intsect-linux-build/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  allow_failure: true

# build_windows:
#   image: julia:1.12-windowsservercore-ltsc2025
#   script: 
#     - apt-get update && apt-get install -y clang make
#     - julia --project=. -e "using Pkg; Pkg.instantiate(); Pkg.add(\"JuliaC\")"
#     - >
#       julia --project=. --startup-file=no -e "using JuliaC; JuliaC.main(ARGS)" --
#       --output-exe intsect
#       --bundle engines/intsect-windows-build
#       --trim=safe
#       --experimental
#       .
#   artifacts:
#     paths:
#       - engines/intsect-windows-build/
#     expire_in: 1 week
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"
#   allow_failure: true


# arenant:
#   image: julia:1.12
#   script: 
#     - export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
#     - chmod +x engines/MzingaEngine engines/nokamute
#     - julia --project=. -e "using Pkg; Pkg.instantiate()"
#     - julia --project=. -e "using Intsect; Arenant.run_arena(; debug=false, time_limit_s=0.1, engines_file=\"./engines/engines_linux.yaml\")" | tee arenant-results.txt
#   artifacts:
#     paths:
#       - arenant-results.txt
#     expire_in: 1 week
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"
#   allow_failure: true